### ISSUE TITLE
running as non-root user - possible?

### ISSUE THREAD

**Issue by michaelkoetter** [democratic-csi/democratic-csi#18] opened 2020-10-13 18:33 UTC
Hi, first of all this looks like a great project, just what I'm looking for :+1: 

I'm wondering if it is possible to run as an unprivileged user with sudo, as my storage server doesn't allow root login via ssh. All the examples only show "root" as user.

It would also be good to know which commands need to be run on the storage server for NFS and iSCSI (so I can create entries in `/etc/sudoers`).

**Comment by travisghansen** [comment] 2020-10-13 21:09
@michaelkoetter hey thanks! What are you using for your storage system?

Just so I'm clear, you are asking about the operations running on the zfs server right, not about running the pods as unprivileged in k8s correct? If so, the underlying code I wrote to handle `zfs` operations does actually have `sudo` support but I don't have a parameter for it in the configs to control it...it would be easy enough to do so though.

Regarding the full list of commands it depends on what your storage system is and what driver exactly you're configured to run. I've been meaning to build up a comprehensive list but it's not a high priority. The list is quite small though:

- `zfs`
- `zpool`

I do have some clone features that use a shell to invoke `zfs send | zfs receive` which could be tricky to replicate with `sudo`.

**Comment by michaelkoetter** [comment] 2020-10-13 21:33
> @michaelkoetter hey thanks! What are you using for your storage system?

I'm running Ubuntu Server 20.04 on both the storage server (basically a NAS with ZoL) and Kubernetes nodes (bare metal), some Ansible and Terraform code to configure everything. 
So I could enable root login (which I did now temporarily to get things running), but would prefer if it was disabled :smiley: 

> Just so I'm clear, you are asking about the operations running on the zfs server right, not about running the pods as unprivileged in k8s correct? 

Yes exactly. Basically everything that is executed using SSH.

> Regarding the full list of commands it depends on what your storage system is and what driver exactly you're configured to run. I've been meaning to build up a comprehensive list but it's not a high priority. The list is quite small though:
> 
> * `zfs`
> * `zpool`
> 
> I do have some clone features that use a shell to invoke `zfs send | zfs receive` which could be tricky to replicate with `sudo`.

For generic ZoL iSCSI I guess `targetcli` needs to be added as well?

As I mentioned above, right now I got it working by enabling root login. I'd be happy to help with testing sudo support whenever it's ready.

**Comment by travisghansen** [comment] 2020-10-13 22:32
Ok great! Yeah it is using targetcli! You’re the first I’m aware of using the zol driver. I’d have to audit the targetcli/share commands as well but it’s pretty small. I’m not sure if I added sudo support for the targetcli stuff but probably easy enough to add.

Let me do some digging and get back at yeah with config details when ready.

In the mean time, if you could share your config (remove any secrets obviously) I’d love to check it out. I usually see stuff I need to document better when I review.

Also, is it working end to end? Do nodes attach and the whole thing? Do you need chap?

**Comment by michaelkoetter** [comment] 2020-10-13 23:29
Sure thing. The config is a bit "special" because it's all written in Terraform HCL, but I think you'll be able to figure it out :smiley: 

Basically I'm using one driver config for both instances (nfs and iscsi), and then add / override some select values in the Helm deployments.
The SSH key is kept in Terraforms state, it outputs the public key at the end which I then added to root's `.ssh/authorized_keys` on the storage server. 

So far it seems to work, but I only ran a few `dbench` tests to check performance. Will probably do some more tests later this week.

`democratic-csi.tf`:
```terraform
locals {
  democratic_csi_driver_config = {
    driver = {
      config = {
        sshConnection = {
          host     = "blackhole-storage"
          port     = 22
          username = "root"
        }

        service = {
          identity   = {}
          controller = {}
          node       = {}
        }

        zfs = {
          datasetEnableQuotas      = true
          datasetEnableReservation = false
          datasetPermissionsMode   = "0777"
          datasetPermissionsUser   = "root"
          datasetPermissionsGroup  = "root"

          zvolEnableReservation = "false"
          zvolBlocksize         = "16K"
        }

        nfs = {
          shareStrategy = "setDatasetProperties"
          shareStrategySetDatasetProperties = {
            properties = {
              sharenfs : "rw,root_squash,no_wdelay"
            }
          }
          shareHost = "blackhole-storage"
        }

        iscsi = {
          shareStrategy = "targetCli"
          shareStragetyTargetCli = {
            basename : "iqn.2003-01.org.linux-iscsi.ubuntu-20"
            tpg = {
              attributes = {
                authentication          = 0
                generate_node_acls      = 1
                cache_dynamic_acls      = 1
                demo_mode_write_protect = 0
              }
            }
          }
          targetPortal  = "blackhole-storage:3260"
          targetPortals = []
        }
      }
    }
  }
}

resource "tls_private_key" "democratic_csi" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "helm_release" "democratic_csi_iscsi" {
  name             = "democratic-csi-iscsi"
  namespace        = "democratic-csi"
  create_namespace = true
  repository       = "https://democratic-csi.github.io/charts/"
  chart            = "democratic-csi"
  version          = "0.4.5"

  values = [jsonencode(local.democratic_csi_driver_config)]

  set {
    name  = "csiDriver.name"
    value = "org.democratic-csi.iscsi"
  }

  set {
    name  = "driver.config.driver"
    value = "zfs-generic-iscsi"
  }

  set {
    name  = "driver.config.zfs.datasetParentName"
    value = "ssdpool/k8s/iscsi"
  }

  set {
    name  = "driver.config.zfs.detachedSnapshotsDatasetParentName"
    value = "ssdpool/k8s/iscsi-snapshots"
  }

  set_sensitive {
    name  = "driver.config.sshConnection.privateKey"
    value = tls_private_key.democratic_csi.private_key_pem
  }

  set {
    name  = "storageClasses[0].name"
    value = "zfs-iscsi"
  }

  set {
    name  = "storageClasses[0].defaultClass"
    value = false
  }

  set {
    name  = "storageClasses[0].reclaimPolicy"
    value = "Delete"
  }

  set {
    name  = "storageClasses[0].volumeBindingMode"
    value = "Immediate"
  }

  set {
    name  = "storageClasses[0].allowVolumeExpansion"
    value = true
  }

  set {
    name  = "storageClasses[0].parameters.fsType"
    value = "ext4"
  }
}

resource "helm_release" "democratic_csi_nfs" {
  name             = "democratic-csi-nfs"
  namespace        = "democratic-csi"
  create_namespace = true
  repository       = "https://democratic-csi.github.io/charts/"
  chart            = "democratic-csi"
  version          = "0.4.5"

  values = [jsonencode(local.democratic_csi_driver_config)]

  set {
    name  = "csiDriver.name"
    value = "org.democratic-csi.nfs"
  }

  set {
    name  = "driver.config.driver"
    value = "zfs-generic-nfs"
  }

  set {
    name  = "driver.config.zfs.datasetParentName"
    value = "ssdpool/k8s/nfs"
  }

  set {
    name  = "driver.config.zfs.detachedSnapshotsDatasetParentName"
    value = "ssdpool/k8s/nfs-snapshots"
  }

  set_sensitive {
    name  = "driver.config.sshConnection.privateKey"
    value = tls_private_key.democratic_csi.private_key_pem
  }

  set {
    name  = "storageClasses[0].name"
    value = "zfs-nfs"
  }

  set {
    name  = "storageClasses[0].defaultClass"
    value = false
  }

  set {
    name  = "storageClasses[0].reclaimPolicy"
    value = "Delete"
  }

  set {
    name  = "storageClasses[0].volumeBindingMode"
    value = "Immediate"
  }

  set {
    name  = "storageClasses[0].allowVolumeExpansion"
    value = true
  }

  set {
    name  = "storageClasses[0].parameters.fsType"
    value = "nfs"
  }

  set {
    name  = "storageClasses[0].mountOptions[0]"
    value = "noatime"
  }
}

output "democratic_csi_ssh_public_key" {
  value = tls_private_key.democratic_csi.public_key_openssh
}

```

**Comment by travisghansen** [comment] 2020-10-14 02:08
Looks like you know your stuff! Yeah all looks good to me in principle so doing good!

Give me a chance to work on sudo options and then you should be all set.

**Comment by lu1as** [comment] 2020-10-27 20:15
I also tried to get it running without root SSH login and just found out that ZFS [supports permission delegation](https://docs.oracle.com/cd/E23824_01/html/821-1448/gfkco.html).
So I created a dataset and a user called `csi` and set the permissions with: 
`zfs allow csi create,destroy,mount,refquota,snapshot,userprop tank/my-dataset`.

Since I use TrueNAS with NFS the remaining share configuration is done via API. Also the user needs the permission to mount datasets, which can be enabled with `sysctl vfs.usermount=1` on BSD (in Linux it's a bit different, but possible, too). Finally the dataset needs to be owned by the csi user, so that he can create mount points.
 
I haven't tried snapshots yet, but basic PV creation and attachment works without root or sudo this way. There're permissions for `zfs send` and `receive`, too, which may makes cloning via pipes easier than with sudo.

**Comment by travisghansen** [comment] 2020-10-27 21:59
Wow! sounds awesome! It would be great to have this documented. I'm usually quicker at addressing issues but you caught me while traveling heavily (and crazy busy for other reasons). I haven't forgotten about this and it won't be difficult to implement but I still won't have time for another couple weeks probably :(

**Comment by michaelkoetter** [comment] 2020-10-29 09:13
Nice find! Unfortunately Linux has some restrictions according to the [man page](https://zfsonlinux.org/manpages/0.8.5/man8/zfs.8.html):

> Delegations are supported under Linux with the exception of *mount unmount mountpoint canmount rename* and *share* These permissions cannot be delegated because the Linux mount(8) command restricts modifications of the global namespace to the root user.

For iSCSI zvols it could work (might still require sudo for targetcli?), but I think NFS needs the "share" command which wouldn't work.

**Comment by kquinsland** [comment] 2020-11-16 00:01
Thanks for putting together this project using the new CIS based system. I've been playing with this provider and have NFS and iSCSI working w/ my microk8s cluster.... as `root`.

Apparently, FreeNAS only supports web access - and thus, API access - via the `root` user. See: https://www.truenas.com/community/threads/more-web-interface-users-then-root.74576/

@lu1as can you share some more details about how you were able to use this driver w/ FreeNAS w/o using `root` credentials?

I can set up SSH access to FreeNAS for users other than root, though, but they appear to not be used?

Is my understanding correct that the basic NFS/iSCSI operations are done via API when targeting FreeNAS and the `ssh` section of the driver is only used for ZoL or generic cases?

**Comment by travisghansen** [comment] 2020-11-16 03:32
Very few actions are performed via the http api with freenas...only the creation of the share(s) for both nfs and iscsi. All zfs actions and chmods etc are done over ssh.

**Comment by lu1as** [comment] 2020-11-16 15:46
@kquinsland I added some details to the README. But as you mentioned, using the API still needs root privileges, so it's only a partial solution for this issue here.

**Comment by travisghansen** [comment] 2020-11-16 15:57
I finally made it home from my trip and will be reviewing this from a sudo perspective shortly and making some minor changes to make sure it works end to end with sudo for the ssh bits. As was mentioned the api is problematic still, however I believe 12 introduced tokens which can be scoped etc so that would resolve that issue if indeed it works the way I think it does.

**Comment by kquinsland** [comment] 2020-11-16 17:52
@lu1as  Thanks for adding some details.  I don't have a time line, but hope to have a complete guide written /published by the end of the month.

@travisghansen There was a version of FreeNas (10 / Coral) that had this feature but it was largely a failure/boondoggle. FreeNas 12 (Now, known as TrueNas) was just released in late october. I am watching the reddit and ixsystems forums for bugs. I'll probably upgrade to 12 when the next point release comes out and once the procedure for migrating from the legacy encryption settings to the new per-dataset encryption scheme are known. If it does offer scoped API tokens then `rootless` may be possible.

I am still wrapping my head around helm, but it may be possible to set the ssh/http credentials as a secret then just point to the secret name in the `values.yaml`. This would allow me to keep the `values.yaml` files in git and help me feel a bit better about leaving root creds to my NAS outside of password manager.

**Comment by travisghansen** [comment] 2020-11-16 19:22
10 may have had something I don’t know. Regarding the secret that should be easy enough to add support in the chart for that. Right now the whole driver config gets created as a secret. I think the best thing to do here would be to add support for creating the secret entirely on your own and not bother updating various places in the app to support pulling in via env var and the like.

The secret gets written out as a yaml file in the container and that’s it. Pretty straightforward.

**Comment by travisghansen** [comment] 2020-11-16 19:22
Also note, the config requires minor adjustments to work with 12 when you decide to do that.

**Comment by kquinsland** [comment] 2020-11-16 19:24
>  I think the best thing to do here would be to add support for creating the secret entirely on your own and not bother updating various places in the app to support pulling in via env var and the like.

That's _exactly_ what I had in mind.

**Comment by travisghansen** [comment] 2020-11-22 00:33
OK folks, images are currently building in the `next` branch to support full root-less operation with `sudo`. Any testing would be appreciated. A couple notes:

- support was added for using `apiKey` (requires TrueNAS-12) instead of username/password: https://github.com/democratic-csi/democratic-csi/blob/next/examples/freenas-iscsi.yaml#L7
- I recommend `sudo` usage over the fancy `zfs allow` stuff simply because I coupled the `sudo` toggle with `zfs` operations to be used for `chmod/chown/setacl/etc` calls that happen. I may split them out in the future but `sudo` seems more extensible generally
- to enable `sudo` for the base provisioner you need to set the value as shown here: https://github.com/democratic-csi/democratic-csi/blob/next/examples/freenas-iscsi.yaml#L30 (applicable in the relevant location for all the zfs based drivers)
- if you are using the `zfs-generic-iscsi` (ie: targetcli) then you **also** need to enable it here as well: https://github.com/democratic-csi/democratic-csi/blob/next/examples/zfs-generic-iscsi.yaml#L54

It may also go without saying but in your `sudoers` config you'll need to ensure the user can invoke without a password.

With all of the above changes, it's fully operational and access could be sanely revoked at any time from the driver. Or if a password/sshkey/apiKey becomes compromised it's easily fixed/revoked without regard to the core administration of the system.

Please deploy with the `next` tag when you get a chance (give an hour or so for the builds to finish though) and report back here with your experiences. Thanks for the input and help!

**Comment by michaelkoetter** [comment] 2020-11-23 10:36
@travisghansen thanks a lot, I will hopefully be able to test it this week.

**Comment by travisghansen** [comment] 2020-11-27 21:30
@michaelkoetter my most recent commit fixed the typo in the config for targetCli, the key in the yaml has changed:

- was `shareStragetyTargetCli`
- is now `shareStrategyTargetCli`

**Comment by travisghansen** [comment] 2020-11-30 18:11
@michaelkoetter ok, the most recent images in `next` are what I will probably snap as version `1.0.0` of the project. I wrapped up support for `sudo` which includes restarting the iscsi daemon using sudo now as well. Given the requirements to do more actions than simply `zfs` (chmod/chown/iscsi daemon reload) I likely can't/won't support the zfs delegation feature as it's unfortunately an incomplete solution :(

I have not tested the targetCli code path so if you get around to it let me know if that works as designed with sudo specifically.

**Comment by travisghansen** [comment] 2020-12-04 00:08
I've just merged all of my enhancements to master. This is now possible by setting the proper fields as explained above in the config. Closing.

**Closed by travisghansen** 2020-12-04 00:08 UTC
